workflows:
  android-keg-scanner:
    name: Keg Scanner Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.kegbatchscanner"
        GOOGLE_SERVICES_JSON: Encrypted(...)
      node: 16
      xcode: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Copy Android Manifest
        script: |
          # Copy the updated manifest with camera permissions
          if [ -f "AndroidManifest.xml" ]; then
            cp AndroidManifest.xml android/app/src/main/AndroidManifest.xml
          fi
      - name: Set up Gradle properties
        script: |
          # Create gradle.properties with proper settings
          cat >> android/gradle.properties << EOF
          # React Native optimizations
          org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+UseParallelGC
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          org.gradle.daemon=true
          
          # Android build optimizations
          android.useAndroidX=true
          android.enableJetifier=true
          android.enableR8=true
          
          # Vision Camera
          disableNewArchitecture=false
          
          # Flipper
          FLIPPER_VERSION=0.125.0
          EOF
      - name: Clean and build Android APK
        script: |
          cd android
          
          # Clean previous builds
          ./gradlew clean
          
          # Build the APK
          ./gradlew assembleRelease --stacktrace
      - name: Verify APK was created
        script: |
          echo "=== Checking for APK files ==="
          find android/app/build/outputs -name "*.apk" -exec ls -lh {} \;
          
          # Check if APK exists
          APK_PATH="android/app/build/outputs/apk/release/app-release.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK built successfully!"
            ls -lh "$APK_PATH"
          else
            echo "❌ APK not found!"
            echo "Available files in build outputs:"
            find android/app/build/outputs -type f
            exit 1
          fi
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - shantu.hasko@ab-inbev.com
        notify:
          success: true
          failure: true
      # Uncomment below for Google Play Store publishing when ready
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true

  # iOS workflow - ONLY uncomment if you need iOS builds and have App Store Connect configured
  # ios-keg-scanner:
  #   name: Keg Scanner iOS Build  
  #   max_build_duration: 60
  #   instance_type: mac_mini_m1
  #   integrations:
  #     app_store_connect: codemagic_app_store_connect
  #   environment:
  #     ios_signing:
  #       distribution_type: app_store
  #       bundle_identifier: com.kegbatchscanner
  #     vars:
  #       XCODE_WORKSPACE: "KegBatchScanner.xcworkspace"
  #       XCODE_SCHEME: "KegBatchScanner"
  #     node: 16
  #     xcode: latest
  #   triggering:
  #     events:
  #       - push
  #       - tag
  #       - pull_request
  #     branch_patterns:
  #       - pattern: main
  #         include: true
  #         source: true
  #   scripts:
  #     - name: Install npm dependencies
  #       script: |
  #         npm install --legacy-peer-deps
  #     - name: Install CocoaPods dependencies
  #       script: |
  #         cd ios && pod install
  #     - name: Set up iOS Info.plist permissions
  #       script: |
  #         # Add camera usage description to Info.plist
  #         /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string" ios/KegBatchScanner/Info.plist || true
  #         /usr/libexec/PlistBuddy -c "Set :NSCameraUsageDescription 'This app needs camera access to scan keg batch codes'" ios/KegBatchScanner/Info.plist
  #     - name: Build iOS app
  #       script: |
  #         cd ios
  #         xcodebuild -workspace KegBatchScanner.xcworkspace -scheme KegBatchScanner -configuration Release -destination generic/platform=iOS -archivePath build/KegBatchScanner.xcarchive archive
  #     - name: Export IPA
  #       script: |
  #         cd ios
  #         xcodebuild -exportArchive -archivePath build/KegBatchScanner.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
  #   artifacts:
  #     - ios/build/*.ipa
  #     - /tmp/xcodebuild_logs/*.log
  #   publishing:
  #     app_store_connect:
  #       auth: integration
  #       submit_to_testflight: true
  #     email:
  #       recipients:
  #         - shantu.hasko@ab-inbev.com
  #       notify:
  #         success: true
  #         failure: true
