workflows:
  android-workflow:
    name: Android Build (APK)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.yourapp"  # optional
      android_signing:
        - keystore_reference

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: |
          npm ci || npm install

      - name: Build Android APK (debug)
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
