workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install JS dependencies
        script: |
          npm ci || npm install

      - name: Build debug APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
